###  사용 DB : MySQL

### 선택한 날짜의 일기 작성
POST http://localhost:8085/create/diary?date=2024-05-04
Content-Type: text/plain

일기 내용을 입력하는 칸입니다. 여기에 입력하면 됩니다.

### 선택한 날짜에 작성한 일기들 가져오기
GET http://localhost:8085/read/diary?date=2024-05-04

### 원하는 범위의 날짜 안의 일기들 가져오기
GET http://localhost:8085/read/diaries?startDate=1803-04-20&endDate=2023-04-20

### 선택한 날짜의 첫번째 일기 내용 수정하기
PUT http://localhost:8085/update/diary?date=2024-05-04
Content-Type: text/plain

현재 날짜의 첫번째 일기를 수정합니다. 일기 내용은 현재 이 내용으로 수정됩니다.

### 선택한 날짜의 일기들 모두 제거하기
DELETE http://localhost:8085/delete/diary?date=2022-06-20